import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = 'cngxjs/compodocx';
const REF = 'develop';

const FILES = [
  { src: 'src/styles/compodocx.css', dst: 'src/styles/vendor/compodocx/compodocx.css' },
  { src: 'src/themes/ocean.css', dst: 'src/styles/vendor/compodocx/themes/ocean.css' },
  { src: 'src/themes/midnight.css', dst: 'src/styles/vendor/compodocx/themes/midnight.css' },
  { src: 'src/themes/nord.css', dst: 'src/styles/vendor/compodocx/themes/nord.css' },
  { src: 'src/themes/rose-pine.css', dst: 'src/styles/vendor/compodocx/themes/rose-pine.css' },
  { src: 'src/themes/ember.css', dst: 'src/styles/vendor/compodocx/themes/ember.css' },
  { src: 'src/themes/neon.css', dst: 'src/styles/vendor/compodocx/themes/neon.css' },
  { src: 'src/themes/brutalist.css', dst: 'src/styles/vendor/compodocx/themes/brutalist.css' },
];

const root = fileURLToPath(new URL('..', import.meta.url));

async function resolveSha() {
  const url = `https://api.github.com/repos/${REPO}/commits/${REF}`;
  const res = await fetch(url, {
    headers: {
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'compodocx-website-sync',
    },
  });
  if (!res.ok) {
    throw new Error(`failed to resolve ${REF} on ${REPO}: ${res.status} ${res.statusText}`);
  }
  const data = await res.json();
  return data.sha;
}

async function fetchFile(sha, srcPath) {
  const url = `https://raw.githubusercontent.com/${REPO}/${sha}/${srcPath}`;
  const res = await fetch(url, { headers: { 'User-Agent': 'compodocx-website-sync' } });
  if (!res.ok) {
    throw new Error(`failed to fetch ${url}: ${res.status} ${res.statusText}`);
  }
  return res.text();
}

function extractTokens(upstream, sha) {
  const themeIndex = upstream.search(/@theme\s*\{/);
  if (themeIndex === -1) {
    throw new Error('could not find @theme block in upstream compodocx.css');
  }
  const header =
    `/* Derived from cngxjs/compodocx@${sha.slice(0, 7)} src/styles/compodocx.css.\n` +
    ` * Generated by scripts/sync-tokens.mjs — do not edit by hand.\n` +
    ` * Component partials and @source directives from upstream are intentionally\n` +
    ` * dropped; only the @theme block and trailing global rules are vendored. */\n\n`;
  return header + upstream.slice(themeIndex);
}

async function main() {
  const sha = await resolveSha();
  const syncedAt = new Date().toISOString();

  console.log(`Syncing tokens from ${REPO}@${sha.slice(0, 7)} (${REF})`);

  for (const file of FILES) {
    const upstream = await fetchFile(sha, file.src);
    const content =
      file.src === 'src/styles/compodocx.css' ? extractTokens(upstream, sha) : upstream;
    const dstPath = join(root, file.dst);
    await mkdir(dirname(dstPath), { recursive: true });
    await writeFile(dstPath, content, 'utf8');
    const note = content !== upstream ? ' [extracted]' : '';
    console.log(`  ${relative(root, dstPath)} (${content.length} bytes)${note}`);
  }

  const lock = {
    source: `https://github.com/${REPO}`,
    ref: REF,
    sha,
    syncedAt,
    files: FILES.map((f) => ({
      dst: f.dst,
      src: f.src,
      mode: f.src === 'src/styles/compodocx.css' ? 'extracted' : 'verbatim',
    })),
  };
  const lockPath = join(root, 'compodocx-tokens.lock.json');
  await writeFile(lockPath, JSON.stringify(lock, null, 2) + '\n', 'utf8');
  console.log(`\nLock file: ${relative(root, lockPath)} (sha ${sha.slice(0, 7)})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
